# Generated by Django 3.0.6 on 2020-05-16 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Bu Alana Sadece Harf Girilebilir!')], verbose_name='Ad')),
                ('surname', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Bu Alana Sadece Harf Girilebilir!')], verbose_name='Soyad')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=32, verbose_name='Şifre')),
                ('lastlogin', models.DateTimeField(auto_now=True, verbose_name='Son Giriş')),
            ],
        ),
    ]
