# Generated by Django 3.0.6 on 2020-05-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Ad')),
                ('surname', models.CharField(max_length=64, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=128, verbose_name='Eposta')),
                ('password', models.CharField(max_length=64, verbose_name='Şifre')),
            ],
        ),
        migrations.DeleteModel(
            name='account',
        ),
    ]
