# Generated by Django 3.0.6 on 2020-06-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kamera553', '0003_alertme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertme',
            name='a_end',
            field=models.TimeField(max_length=5, verbose_name='Başlangıç Saati'),
        ),
        migrations.AlterField(
            model_name='alertme',
            name='a_start',
            field=models.TimeField(max_length=5, verbose_name='Başlangıç Saati'),
        ),
    ]
