# Generated by Django 3.0.6 on 2020-06-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kamera553', '0004_auto_20200620_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cam_image',
            field=models.ImageField(default=25, upload_to='', verbose_name='Kamera Anlık Feed'),
            preserve_default=False,
        ),
    ]
