# Generated by Django 3.0.6 on 2020-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kamera553', '0006_auto_20200620_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_insansay', models.IntegerField(verbose_name='İnsan Sayısı')),
                ('r_tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='cam_period',
            field=models.IntegerField(default=0, verbose_name='Periyot'),
            preserve_default=False,
        ),
    ]
