# Generated by Django 3.0.6 on 2020-06-21 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kamera553', '0007_auto_20200621_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cam_image',
            field=models.BinaryField(null=True, verbose_name='Kamera Anlık Feed'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='cam_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Kamera Adı'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='cam_period',
            field=models.IntegerField(default=1, verbose_name='Periyot'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='r_tarih',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Tarih'),
        ),
    ]
