# Generated by Django 3.0.6 on 2020-06-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kamera553', '0010_auto_20200622_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertme',
            name='a_status',
            field=models.BooleanField(default=False, verbose_name='Kamerda Alarm Durumu'),
        ),
    ]
