# Generated by Django 3.0.6 on 2020-06-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kamera553', '0011_alertme_a_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertme',
            name='a_status',
            field=models.BooleanField(default=True, verbose_name='Kamerda Alarm Durumu'),
        ),
    ]
