# Generated by Django 3.0.6 on 2020-06-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kamera553', '0012_auto_20200623_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cam_ownermail',
            field=models.CharField(default=55, max_length=256, verbose_name='Kamera Sahip Email'),
            preserve_default=False,
        ),
    ]
